project/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from haystack.views import SearchView
from project.forms import LoginUserForm, CustomForm
from project.views import (BlogPostCreate, HomePageView, BlogPostDetail, 
	        BlogPostUpdate, BlogPostDelete, ProfileBlog, UserDashboard,
	        BlogTags, AboutPageView, FollowUser, UnfollowUser,
            UserFollowers, UserFollowing, FavoritePost, UnfavoritePost,
            FavsView, RegistrationRedirect, UserFeed)

urlpatterns = patterns('',
	url(r'^$', HomePageView.as_view(), name='homepage'),
    url(r'^accounts/register/$', RegistrationRedirect.as_view(), name='reg_redirect'),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'registration/login.html', 'authentication_form': LoginUserForm}),
    url(r'about/$', AboutPageView.as_view(), name='about'),
    url(r'create/$', login_required(BlogPostCreate.as_view()), name='create'),
    url(r'(?P<id>\d+)/(?P<slug>[\w-]+)/$', BlogPostDetail.as_view(), name='detail'),
    url(r'(?P<id>\d+)/(?P<slug>[\w-]+)/update/$', login_required(BlogPostUpdate.as_view()), name='update'),
    url(r'(?P<id>\d+)/(?P<slug>[\w-]+)/delete/$', login_required(BlogPostDelete.as_view()), name='delete'),
    url(r'(?P<id>\d+)/(?P<slug>[\w-]+)/favorite/$', login_required(FavoritePost.as_view()), name='favorite'),
    url(r'(?P<id>\d+)/(?P<slug>[\w-]+)/unfavorite/$', login_required(UnfavoritePost.as_view()), name='unfavorite'),
    url(r'tag/(?P<tag>[\w-]+)/$', BlogTags.as_view(), name='tagged_posts'),
    url(r'dashboard/$', login_required(UserDashboard.as_view()), name='user_dashboard'),
    url(r'^(?P<author>[\w-]+)/$', ProfileBlog.as_view(), name='profile_detail'),
    url(r'^(?P<author>[\w-]+)/follow$', login_required(FollowUser.as_view()), name='follow_user'),
    url(r'^(?P<author>[\w-]+)/unfollow$', login_required(UnfollowUser.as_view()), name='unfollow_user'),
    url(r'^(?P<author>[\w-]+)/followers/$', UserFollowers.as_view(), name='user_followers'),
    url(r'^(?P<author>[\w-]+)/following/$', UserFollowing.as_view(), name='user_following'),
    url(r'^(?P<author>[\w-]+)/favorites/$', FavsView.as_view(), name='user_favs'),
    url(r'^home/search/', SearchView(form_class=CustomForm), name='haystack_search'),
    url(r'^home/feed/', login_required(UserFeed.as_view()), name='user_feed'),
)

test_project/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'test_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls'))
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('project.urls', namespace='project')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^home/search/', include('haystack.urls')),
)

project/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

class BlogPost(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    content = models.TextField()
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField()
    hits = models.PositiveIntegerField(default=0)
    
    def save(self, *args, **kwargs):
    	""" Auto saves title as slug, and user as author. """
        self.slug = slugify(self.title)
        self.author = self.user.username
        super(BlogPost, self).save(*args, **kwargs)
		
    def __unicode__(self):
        return self.title

class BlogPostTags(models.Model):
    tag = models.CharField(max_length=100)
    blog_posts = models.ManyToManyField(BlogPost)

    def __str__(self):
        return self.tag
        
class UserProfile(models.Model):
    user = models.OneToOneField(User)
    favorites = models.ManyToManyField(BlogPost,
        related_name='favorited')
    following = models.ManyToManyField('self',
        related_name='followers',
        symmetrical=False)
    
    def __unicode__(self):
        return self.user.username

project/forms.py
from django import forms
from haystack.forms import SearchForm
from django.forms import ModelForm, CharField
from project.models import BlogPost, BlogPostTags
from django.core.validators import validate_slug
from registration.forms import RegistrationForm
from django.contrib.auth.forms import AuthenticationForm
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget

class BlogForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        """ Override init to set required status """
        super(BlogForm, self).__init__(*args, **kwargs)
        self.fields['content'].required = True
        self.fields['title'].required = True

    class Meta:
        model = BlogPost
        fields = ['title', 'content']
        widgets = {
        'content': SummernoteWidget(),
        'title': forms.TextInput(attrs={'class': 'form-control',
                                        'placeholder': 'Title',}),
        }

class BlogPostTagsForm(forms.ModelForm):

    tag = forms.CharField(
        validators=[validate_slug],
        widget=forms.TextInput(
            attrs={
            'class': 'form-control',
            'placeholder': 'Add your tag'
            }
        ))
        
    class Meta:
        model = BlogPostTags
        fields = ['tag']
        
        
class UserRegistrationForm(RegistrationForm):
    """
    Subclass of RegistrationForm to add bootstrap
    components to reg form
    """
    username = forms.RegexField(
        regex=r'^\w+$',
        max_length=30,
        widget=forms.TextInput(
            attrs={
            'class': 'form-control',
            'placeholder': 'Username',
            }
    ))

    email = forms.CharField(widget=forms.TextInput(
        attrs={
        'class': 'form-control',
        'placeholder': 'Email',
        }
    ))

    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={
        'class': 'form-control',
        'placeholder': 'Password',
        }
    ))

    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={
        'class': 'form-control',
        'placeholder': 'Password (again)',
        }
    ))

class LoginUserForm(AuthenticationForm):
    """
    Subclass auth form to user bootstrap
    form-control and placeholder
    """
    username = forms.CharField(
        max_length=254,
        widget=forms.TextInput(
            attrs={
            'class': 'form-control',
            'placeholder': 'Username',
            }
    ))

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
            'class': 'form-control',
            'placeholder': 'Password',
            }
    ))

class CustomForm(SearchForm):
    
    q = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
            'type': 'search',
            'class': 'form-control',
            'placeholder': 'Username, Title, or Content Keyword',
            }
    ))

    def search(self):
        sqs = super(CustomForm, self).search()
        return sqs

project/views.py
from collections import Counter
from django.contrib import messages
from django.shortcuts import redirect
from haystack.views import SearchView
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from registration.backends.simple.views import RegistrationView
from project.models import BlogPost, BlogPostTags, UserProfile
from django.shortcuts import get_list_or_404, get_object_or_404
from project.forms import (BlogForm, BlogPostTagsForm, UserRegistrationForm,
                    LoginUserForm)
from django.views.generic import (ListView, CreateView, DetailView,
                    UpdateView, DeleteView, TemplateView, FormView,
                    View)

class HomePageView(ListView):
    """ Lists all blog posts for every user. """
    model = BlogPost
    template_name = 'project/index.html'
    context_object_name = 'all_posts'
    paginate_by = 10

    def get_queryset(self):
        """ All posts sorted by date added """
        all_posts = super(HomePageView, self).get_queryset()
        return all_posts.order_by('-added')

    def get_context_data(self, **kwargs):
        """
        Returns all tags, and used item_count to sort by popular.
        Also returns top 5 most popular posts based on hits.
        """
        context = super(HomePageView, self).get_context_data(**kwargs)
        get_tags = BlogPostTags.objects.all()
        context['tag_count'] = self.item_count(get_tags)
        context['popular_posts'] = BlogPost.objects.all().order_by('-hits')[:5]
        return context

    def item_count(self, tags):
    	""" Creates tuple of tags by most popular, and provides count """
        clean_tags = [str(tag) for tag in tags]
        c = Counter(clean_tags)
        return c.most_common()

class RegistrationRedirect(RegistrationView):
    """
    Overrides default django-reg redirect
    and returns new user to homepage.
    """
    form_class = UserRegistrationForm

    def get_success_url(self, request, user):
        return reverse('project:homepage')

class AboutPageView(TemplateView):
	""" Basic About page """
	model = BlogPost
	template_name = 'project/about.html'

class BlogPostDetail(SuccessMessageMixin, FormView):
    """ Single blog post content viewable by all users. """
    model = BlogPost
    form_class = BlogPostTagsForm
    template_name = 'project/blogpost_list.html'
    success_message = 'Tag added!'

    def get_context_data(self, **kwargs):
        """ Gets post, and tags for post by id """
        context = super(BlogPostDetail, self).get_context_data(**kwargs)
        self.id = self.kwargs['id']
        current_post = BlogPost.objects.get(id=self.id)
        context['blog_post'] = current_post
        context['tags'] = BlogPost.objects.get(
            id=self.id).blogposttags_set.all()

        # works for now, but makes more queries than preferred
        # need to revisit later
        context['blog_post'].hits += 1
        context['blog_post'].save()

        """
        Checks if favorite exists already.
        Un-auth'd user has no user object, so typeerror exists.
        Catching the error below forces un-auth'd user to login or reg
        if they click fav, and allows the page to load.
        """
        try:
            me, created = UserProfile.objects.get_or_create(
                user=self.request.user)
            if current_post in me.favorites.all():
                context['favorite_exists'] = True
            else:
                context['favorite_exists'] = False
        except TypeError:
            context['favorite_exists'] = False

        return context

    def form_valid(self, form):
    	""" Uses url param id to query current post """
        self.blog_id = self.kwargs['id']
        self.blog_tag = form.cleaned_data['tag'].lower()
        tag_exists = BlogPostTags.objects.filter(
        	blog_posts__id=self.blog_id).filter(
        	tag=self.blog_tag).exists()

        if not tag_exists:
	        """ 
	        Checks if tag exists, then saves to M2M.
	        Uses slug validation to ensure no spaces in tag.
	        """
	        current_blog = BlogPost.objects.get(id=self.blog_id)
	        add_tag = BlogPostTags(tag=self.blog_tag)
	        add_tag.save()
	        add_tag.blog_posts.add(current_blog)
	        return super(BlogPostDetail, self).form_valid(form)
        else:
            messages.error(
                self.request,
                'The tag "{0}" already exists for this post!'.format(
                    self.blog_tag))
            return super(BlogPostDetail, self).form_invalid(form)

    def get_success_url(self):
		""" Returns user to original blog post """
		return reverse('project:detail', kwargs={
			'id': self.kwargs['id'],
			'slug': self.kwargs['slug'],
			})

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

class BlogPostCreate(CreateView):
    """ Requires login, and saves to logged in user. """
    form_class = BlogForm
    template_name = 'project/blogpost_form.html'

    def form_valid(self, form):
        """ Attributes blog post to "user" foreignkey from models. """
        form.instance.user = self.request.user
        return super(BlogPostCreate, self).form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Both fields are required')
        return self.render_to_response(self.get_context_data(form=form))

    def get_queryset(self):
    	""" 
    	Gets user's blog post queryset.
    	Used with below reverse after post is created
    	"""
        user_set = super(BlogPostCreate, self).get_queryset()
        return user_set.filter(user=self.request.user)

    def get_success_url(self):
        return reverse('project:detail', kwargs={
            'id': self.object.id,
            'slug': self.object.slug,
            })

class ProfileBlog(ListView):
    """ Lists all posts by specific user """
    model = BlogPost
    template_name = 'project/profile_blog.html'

    def get_context_data(self, **kwargs):
        context = super(ProfileBlog, self).get_context_data(**kwargs)
        context['author_posts'] = BlogPost.objects.filter(
            author=self.kwargs['author'])
        context['author'] = self.kwargs['author']
        
        # get or user and author objects
        user_follow, user_created = User.objects.get_or_create(
            username=self.kwargs['author'])
        
        # return following/follower count
        user_follows, created = UserProfile.objects.get_or_create(user=user_follow)
        context['all_following'] = user_follows.following.all()
        context['all_followers'] = user_follows.followers.all()

        try:
            # check if user is already following the author
            me, created_me = UserProfile.objects.get_or_create(
                user=self.request.user)
            context['follow_exists'] = me.following.filter(
                user=user_follow).exists()
        except TypeError:
            # users not logged in raise TypeError
            # self.request.user does not exist for users not logged in
            context['follow_exists'] = None

        return context


class BlogPostUpdate(UpdateView):
	""" Requires login, and only post author can edit. """
	model = BlogPost
	form_class = BlogForm

	def get_queryset(self):
		""" 
		Overrides default queryset to only allow post creator
		to update, and raises 404 error otherwise.
		"""
		user_set = BlogPost.objects.filter(id=self.kwargs['id'])
		return user_set.filter(user=self.request.user)

	def get_success_url(self):
		return reverse('project:detail', kwargs={
			'id': self.object.id,
			'slug': self.object.slug,
			})

class BlogPostDelete(DeleteView):
    """ Requires login, and only post author can delete """
    model = BlogPost
    success_url = reverse_lazy('project:user_dashboard')

    def get_queryset(self):
        """
        Query by id instead of slug to
        avoid duplicate issues.
        """
        messages.success(self.request, 'Post deleted')
        user_set = BlogPost.objects.filter(id=self.kwargs['id'])
        return user_set.filter(user=self.request.user)

class UserDashboard(ListView):
    """ Dashboard where a user can view/edit/delete their posts """
    model = BlogPost
    template_name = 'project/user_profile.html'

    def get_queryset(self):
        """ Queries posts by auth'd user """
        user_posts = super(UserDashboard, self).get_queryset()
        return user_posts.filter(author=self.request.user).order_by('-added')

    def get_context_data(self, **kwargs):
        """ Uses auth'd user as context var to template """
        context = super(UserDashboard, self).get_context_data(**kwargs)
        context['user'] = self.request.user
        return context

class BlogTags(ListView):
	""" Lists blog posts with a certain tag """
	model = BlogPostTags
	template_name = 'project/tag_blogs.html'

	def get_context_data(self, **kwargs):
		""" 
		Returns tag name from url to template,
        and queries for posts with tag
        """
		context = super(BlogTags, self).get_context_data(**kwargs)
		self.tag = self.kwargs['tag']
		context['tag'] = self.kwargs['tag']
		context['tagged_posts'] = BlogPost.objects.filter(
			blogposttags__tag=str(self.tag)).order_by('-added')
		return context

class UserFollowers(ListView):
    """ Lists all followers for a given user """
    model = UserProfile
    template_name = 'project/user_followers.html'

    def get_context_data(self, **kwargs):
       context = super(UserFollowers, self).get_context_data(**kwargs)
       context['author'] = self.kwargs['author']

       # get author object
       user_follow = get_object_or_404(User, username=self.kwargs['author'])

       # return author's followers
       user_follows = get_object_or_404(UserProfile, user=user_follow)

test_project/templates/project/about.html
{% extends "project/base.html" %}
{% load staticfiles %}

{% block title %}About - MorningBlog{% endblock %}

{% block about %}
<li class="active">
  <a href="{% url 'project:about' %}">About</a>
</li>
{% endblock %}

{% block content %}
<ul>

	<h3>About</h3>

</ul>
{% endblock %}

test_project/templates/project/base.html
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load staticfiles %}
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link href='http://fonts.googleapis.com/css?family=Ubuntu&subset=latin,cyrillic-ext' rel='stylesheet' type='text/css'>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../bower_components/html5shiv/dist/html5shiv.js"></script>
      <script src="../bower_components/respond/dest/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <a href="{% url 'project:homepage' %}" class="navbar-brand">MorningBlog</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            {% if user.is_authenticated %}
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes">Profile <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="themes">
                <li><a href="{% url 'project:user_dashboard' %}">Dashboard</a></li>
                <!-- Divider for later use 
                <li class="divider"></li> -->
              </ul>
            </li>

              {% block create_new %}
              <li>
                <a href="{% url 'project:create' %}">Create New Post</a>
              </li>
              {% endblock %}

            {% endif %}

              {% block about %}
              <li>
                <a href="{% url 'project:about' %}">About</a>
              </li>
              {% endblock %}
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a href="{% url 'project:profile_detail' author=user.username %}">{{ user.username }}</a></li>
            <li><a href="/accounts/logout?next=/">Logout</a></li>
            {% else %}
            <li><a href="/accounts/login">Log in</a></li>
            <li><a href="/accounts/register">Create Account</a></li>
            {% endif %}
             <li><a href="/home/search"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></a></li>
          </ul>

        </div>
      </div>
    </div>

  <div class="container">
    <div class="row">

      {% block content %}
        <div class="col-sm-9" style="background-color: white;">
      {% endblock %}

{% if is_paginated %}
<nav>
  <ul class="pager">
  {% if page_obj.has_previous %}
    <li><a href="/?page={{ page_obj.previous_page_number }}"><span aria-hidden="true">&larr;</span> Previous</a></li>
  {% endif %}
  {% if page_obj.has_next %}
    <li><a href="/?page={{ page_obj.next_page_number }}">Next <span aria-hidden="true">&rarr;</span></a></li>
  {% endif %}
  ({{ page_obj.number }} of {{ page_obj.paginator.num_pages }})
  </ul>
</nav>
{% endif %}

        </div>

      {% block sidebar %}{% endblock %}

    </div>
  </div>

   <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script type="text/javascript">
        $(function () {
        $('[data-toggle="tooltip"]').tooltip()
          })  
    </script>

  </body>
</html>

test_project/templates/project/blog_user.html
Test
<ul>
    {% for post in object_list %}
        <li><h5><a href="{% url "project:blog_content" post.pk post.slug %}">{{ post.title }}</a>
         | by: {{ post.author }}</h5></li>
    {% endfor %}
</ul>

test_project/templates/project/blogpost_list.html
{% extends "project/base.html" %}
{% load staticfiles %}

{% block title %}{{blog_post.title|title }} - MorningBlog{% endblock %}

{% block content %}

<h1>{{ blog_post.title|title }}</h1>
	<h5>
		Author: <a href="{% url 'project:profile_detail' blog_post.author %}">{{ blog_post.author }}</a> | Added: {{ blog_post.added }} | Updated: {{ blog_post.updated }} | 
	{% if favorite_exists %}
		<a title="Remove From Favorites" data-toggle="tooltip" href="{% url "project:unfavorite" id=blog_post.id slug=blog_post.slug %}">
			<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
		</a>
	{% else %}
		<a title="Add To Favorites" data-toggle="tooltip" href="{% url "project:favorite" id=blog_post.id slug=blog_post.slug %}">
			<span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
		</a>
	{% endif %}
	</h5>
	<p>{{ blog_post.content|safe }}</p>


{% if blog_post.author == user.username %}
	{% for message in messages %}
		<div class="alert alert-info" role="alert">
			<p>{{ message }}</p>
		</div>
	{% endfor %}

	<div class="col-sm-2" style="background-color: white;">
		<form action="" method="post">
			{% csrf_token %}
			{{ form.tag }}
			<p><button class="btn btn-primary" type="submit">Add Tag</button></p>
		</form>
	</div>
</div>

{% endif %}


<p><span class="glyphicon glyphicon-tags" aria-hidden="true">
	  {% if tags %}
		{% for item in tags %}
		 <a href="{% url "project:tagged_posts" item.tag %}">
		 	<button type="button" class="btn btn-default btn-sm">
		 		{{ item.tag }}
		 	</button>
		 </a>
		{% endfor %}
      {% else %}
		Untagged
	  {% endif %}
</span>
</p>

{% endblock %}

test_project/templates/project/index.html
{% extends "project/base.html" %}
{% load staticfiles %}

{% block title %}MorningBlog{% endblock %}

{% block content %}
<div class="col-sm-9" style="background-color: white;">


<ul>
    {% for post in all_posts %}
        <h3><a href="{% url 'project:detail' post.pk post.slug %}">{{ post.title|title }}</a></h3>
         <h5>
         	Author: <a href="{% url 'project:profile_detail' post.author %}">{{ post.author }}</a>
         	 | Added: {{ post.added }} | Updated: {{ post.updated }}
         </h5>
         <p>
	         {{ post.content|safe|truncatechars:425 }}
	         <a href="{% url 'project:detail' post.pk post.slug %}">Read More</a>
	       </p>
    {% endfor %}
</ul>


{% endblock %}

{% block sidebar %}

      <div class="col-sm-3" style="background-color: none;">
        <h5>Popular Posts:</h5>
          {% for post in popular_posts %}
            <p>
              <a href="{% url 'project:detail' post.pk post.slug %}">
              {{ post.title|title }}</a> ({{ post.hits }})<br>
              <span class="sidebar-author">
                <a href="{% url 'project:profile_detail' post.author %}">{{ post.author }}</a>
              </span>
            </p>
          {% endfor %}
          
      	<h5>Popular Tags:</h5>
      	{% for tag, count in tag_count|slice:"8" %}
      	<a href="{% url "project:tagged_posts" tag %}">
		 	<button type="button" class="btn btn-default btn-sm">
		 		{{ tag }} ({{ count }})
		 	</button>
	 	    </a>
      	{% endfor %}


    </div>

{% endblock %}

test_project/templates/project/profile_blog.html
{% extends "project/base.html" %}

{% block title %}{{ author }} - MorningBlog{% endblock %}

{% block content %}

 <div class="col-sm-9" style="background-color: white;">

<ul>
    <h4>
        {{ author }}

      {% if user.is_authenticated and user.username != author %}
        {% if follow_exists %}
        <a href="{% url "project:unfollow_user" author %}">
            <button type="button" class="pull-right btn btn-default btn-sm">Unfollow</button>
         </a>
        {% else %}
        <a href="{% url "project:follow_user" author %}">
            <button type="button" class="pull-right btn btn-primary btn-sm">Follow</button>
         </a>
        {% endif %}
       {% endif %}
      {% if not user.is_authenticated %}
        <a href="/accounts/login/">
            <button type="button" class="pull-right btn btn-primary btn-sm">Follow</button>
         </a>
      {% endif %}
    </h4>

        <h5>
            Posts: {{ author_posts|length }}
        </h5>
        <h5>
            Following: <a href="{% url 'project:user_following' author %}">{{ all_following|length }}</a>
        </h5>
        <h5> 
            Followers: <a href="{% url 'project:user_followers' author %}">{{ all_followers|length }}</a>
        </h5>
        <h5>
            <a href="{% url 'project:user_favs' author %}">Favorite Posts</a>
        </h5>

    
        {% if author_posts %}
            {% for post in author_posts %}
                <h3><a href="{% url 'project:detail' post.pk post.slug %}">{{ post.title|title }}</a></h3>
                 <h5>
                 	Author: {{ post.author }}
                 	 | Added: {{ post.added }} | Updated: {{ post.updated }}
                 </h5>
                 <p>
        	         {{ post.content|safe|truncatechars:425 }}
        	         <a href="{% url 'project:detail' post.pk post.slug %}">Read More</a>
        	     </p>
            {% endfor %}
        {% else %}
                <h5>No posts found</h5>
        {% endif %}
</ul>

{% endblock %}

test_project/templates/project/user_profile.html
{% extends "project/base.html" %}
{% load staticfiles %}

{% block title %}Dashboard - {{ user.username }} - MorningBlog{% endblock %}

{% block content %}
 <div class="col-sm-9" style="background-color: white;">

<p>
	<h3>
		Dashboard | {{ user.username }}
	</h3>
</p>
<br>
	{% for message in messages %}
		<div class="alert alert-info" role="alert">
			<p>{{ message }}</p>
		</div>
	{% endfor %}

<ul>
    {% for post in object_list %}
	        		<p>
	        			<h4>
	        				<a href="{% url "project:detail" post.pk post.slug %}">{{ post.title|title }}</a><br>
	        				<h5>Added: {{ post.added }} | Updated: {{ post.updated }}</h5>
	        			</h4>	
	        		</p>
		        		<a href="{% url "project:update" post.pk post.slug %}">
		        			<button type="button" class="btn btn-default btn-sm">Update</button>
		        		</a> 
		        		<a href="{% url "project:delete" post.pk post.slug %}">
		        			<button type="button" class="btn btn-danger btn-sm">Delete</button>
		        	</a>
    {% endfor %}
</ul>
{% endblock %}

{% block sidebar %}

<p>		
	<h5>
			<p>Posts: {{ object_list|length }}</p>
			<p>Last Post: {{ object_list.0.added }}</p>
			<p>Joined: {{ user.date_joined }}</p>
			<p>Last Login: {{ user.last_login }}</p>
	</h5>
</p>

{% endblock %}